# kind cluster configuration for local development
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: antidetect
networking:
  # apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
# Control plane node
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # NGINX Ingress
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # API port
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
# Worker nodes
- role: worker
  extraMounts:
  - hostPath: /dev/shm
    containerPath: /dev/shm
  labels:
    workload: browser
- role: worker
  extraMounts:
  - hostPath: /dev/shm
    containerPath: /dev/shm
  labels:
    workload: browser
- role: worker
  labels:
    workload: api
